name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün otomatik güncelleme (UTC)
  workflow_dispatch:  # Manuel olarak çalıştırmak için

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
